import {
	makeObservable,
	observable,
	action,
} from 'mobx';

export default class ShopsStore {
	owner = 'Paris May';
	
	clothesShopData = [
		{
			image: 'tShirt.svg',
			isInStock: false,
			price: 15000,
			component: 0,
			drawable: 1,
			textures: [1, 2, 5, 6, 7],
		}, // 0
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 20000,
			component: 0,
			drawable: 2,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 5000,
			component: 0,
			drawable: 3,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 4,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 5,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 6,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 7,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 8,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 9,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 10,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 11,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 12,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 13,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 14,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 15,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 0,
			drawable: 16,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 15000,
			component: 11,
			drawable: 1,
			textures: [1, 2, 5, 6, 7],
		}, // 11
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 20000,
			component: 11,
			drawable: 2,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 5000,
			component: 11,
			drawable: 3,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 4,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 5,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 6,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 7,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: false,
			price: 13000,
			component: 11,
			drawable: 8,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 9,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 10,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 11,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 12,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 13,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 14,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 15,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 11,
			drawable: 16,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 15000,
			component: 8,
			drawable: 1,
			textures: [1, 2, 5, 6, 7],
		}, // 8
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 20000,
			component: 8,
			drawable: 2,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 5000,
			component: 8,
			drawable: 3,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 4,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 5,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 6,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 7,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 8,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: false,
			price: 13000,
			component: 8,
			drawable: 9,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 10,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 11,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 12,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 13,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 14,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 15,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 8,
			drawable: 16,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 15000,
			component: 4,
			drawable: 1,
			textures: [1, 2, 5, 6, 7],
		}, // 4
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 20000,
			component: 4,
			drawable: 2,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 5000,
			component: 4,
			drawable: 3,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 4,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 5,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 6,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 7,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: false,
			price: 13000,
			component: 4,
			drawable: 8,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 9,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 10,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 11,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 12,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 13,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 14,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 15,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 4,
			drawable: 16,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 15000,
			component: 6,
			drawable: 1,
			textures: [1, 2, 5, 6, 7],
		}, // 6
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 20000,
			component: 6,
			drawable: 2,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 5000,
			component: 6,
			drawable: 3,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 4,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 5,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 6,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 7,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 8,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: false,
			price: 13000,
			component: 6,
			drawable: 9,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 10,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 11,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 12,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 13,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 14,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 15,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 6,
			drawable: 16,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 15000,
			component: 7,
			drawable: 1,
			textures: [1, 2, 5, 6, 7],
		}, // 7
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 20000,
			component: 7,
			drawable: 2,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 5000,
			component: 7,
			drawable: 3,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 4,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 5,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 6,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 7,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 8,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 9,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: false,
			price: 13000,
			component: 7,
			drawable: 10,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 11,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 12,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 13,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 14,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 15,
			textures: [1, 2, 5, 6, 7],
		},
		{
			image: 'tShirt.svg',
			isInStock: true,
			price: 13000,
			component: 7,
			drawable: 16,
			textures: [1, 2, 5, 6, 7],
		},
	];
	weaponShopData = {
		categories: [
			{
				name: 'melee',
				icon: 'meleeCategory.svg',
				guns: [
					{
						name: 'knife',
						icon: 'ak47WeaponList.svg',
						descriptionIcon: 'mp5Weapon.svg',
						params: {
							damage: 80,
							speed: 10,
							accuracy: 100,
							range: 50,
						},
						price: 1000,
						description: 'Weapon description'
					},
				],
			},
			{
				name: 'pistols',
				icon: 'pistolsCategory.svg',
				guns: [
					{
						name: 'Desert Eagle .50',
						icon: 'ak47WeaponList.svg',
						descriptionIcon: 'mp5Weapon.svg',
						params: {
							damage: 40,
							speed: 60,
							accuracy: 70,
							range: 70,
						},
						modifiers: [
							{
								name: 'silencer',
								price: 500,
								isPlaced: false,
							},
							{
								name: 'scope',
								price: 500,
								isPlaced: false,
							},
							{
								name: 'clip',
								price: 500,
								isPlaced: false,
							},
						],
						price: 2000,
						description: 'Weapon description',
						maxAmmo: 100,
						ammoPrice: 5,
					},
				],
			},
		],
	};
	weaponBuyList = [];
	
	constructor() {
		makeObservable(this, {
			owner: observable,
			clothesShopData: observable,
			weaponShopData: observable,
			weaponBuyList: observable,
			
			fetchClothesShopData: action.bound,
			setOwner: action.bound,
			fetchWeaponShopData: action.bound,
			addWeaponBuyListElement: action.bound,
			removeWeaponBuyListElement: action.bound,
			clearWeaponBuyList: action.bound,
		});
	}
	
	fetchClothesShopData(array) {
		return this.clothesShopData = array;
	}
	
	setOwner(name) {
		return this.owner = name;
	}
	
	fetchWeaponShopData(obj) {
		return this.weaponShopData = obj;
	}
	
	addWeaponBuyListElement(obj) {
		const index = this.weaponBuyList.findIndex(el => el.name === obj.name);
		let _obj;
		
		if (index >= 0) return this.weaponBuyList[index].count += 1;
		else {
			if (obj.modifiers) {
				let price;
				if (obj.modifiers.filter(el => el.isPlaced).length > 0)
					price = obj.modifiers.filter(el => el.isPlaced).reduce((acc, curr) => acc + curr);
				else price = 0;
				
				_obj = {
					name: obj.name,
					icon: obj.icon,
					hash: obj.hash,
					count: 1,
					price: obj.price + price,
				};
			} else _obj = {
				name: obj.name,
				icon: obj.icon,
				hash: obj.hash,
				count: 1,
				price: obj.price,
			}
			
			return this.weaponBuyList.push(_obj);
		}
	}
	
	removeWeaponBuyListElement(id) {
		return this.weaponBuyList.splice(id, 1);
	}
	
	clearWeaponBuyList() {
		return this.weaponBuyList = [];
	}
	
	destroy() {
	}
}